from state import CollegeState
from utils.llm import get_llm_response

def response_agent(state: CollegeState):
    """
    Final Response Agent.
    Returns the response generated by the selected agent.
    """

    return state